name: "Deploy"


on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload new release
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body_path: CHANGELOG.txt
          repository: NeutralPlasma/test_deploy_repo
          files: test.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN}}